<footer class="page-footer">
	<div class="container">
		<div class="row">
			<div class="col l3 s12 left">
				<h5 class="white-text">Contact Us!</h5>
					<ul>
						<li>hchun4@u.rochester.edu</li>
						<li>rcricchi@u.rochester.edu</li>
						<li>tmadway@gmail.com</li>
					</ul>
			</div>
		</div>
	</div>

	<div class="footer-copyright">
		<div class="container">
			<div>CSC 174: Group Project #2</div>
			<div>©2017 Hillary Chun, Rose Cricchio, Tori Madway</div>
		</div>
	</div>
</footer>